url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/nbitcorp" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
destination: "/docs"
plugins:
  - github-pages
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
sass:
    load_paths:
        - _sass
        - node_modules
exclude:
 - node_modules